#!/usr/bin/with-contenv sh

# unless this has already been defined, set
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

#if [ ! -d "/opt/daspanel/data/tenant" ]; then
#	mkdir -p /opt/daspanel/data/tenant
#fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/containers" ]; then
	mkdir -p /opt/daspanel/data/$DASPANEL_SYS_UUID/containers
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/content" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/content"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/db" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/db"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/sessions" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/sessions"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/upload" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/upload"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/upload/tmp" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/upload/tmp"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/content" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/content"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs/_account" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs/_account"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/letsencrypt" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/letsencrypt"
fi

if [ ! -d "/opt/daspanel/log/$DASPANEL_SYS_UUID/apiserver" ]; then
	mkdir -p "/opt/daspanel/log/$DASPANEL_SYS_UUID/apiserver"
fi


